// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	service "github.com/xabinapal/gopve/pkg/service"
)

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

// HA provides a mock function with given fields:
func (_m *Cluster) HA() service.HighAvailability {
	ret := _m.Called()

	var r0 service.HighAvailability
	if rf, ok := ret.Get(0).(func() service.HighAvailability); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.HighAvailability)
		}
	}

	return r0
}
