// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pool "github.com/xabinapal/gopve/pkg/types/pool"
)

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *Pool) Get(id string) (pool.Pool, error) {
	ret := _m.Called(id)

	var r0 pool.Pool
	if rf, ok := ret.Get(0).(func(string) pool.Pool); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pool.Pool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *Pool) List() ([]pool.Pool, error) {
	ret := _m.Called()

	var r0 []pool.Pool
	if rf, ok := ret.Get(0).(func() []pool.Pool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pool.Pool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
