// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	task "github.com/xabinapal/gopve/pkg/types/task"
)

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

// Get provides a mock function with given fields: upid
func (_m *Task) Get(upid string) (task.Task, error) {
	ret := _m.Called(upid)

	var r0 task.Task
	if rf, ok := ret.Get(0).(func(string) task.Task); ok {
		r0 = rf(upid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(upid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *Task) List() ([]task.Task, error) {
	ret := _m.Called()

	var r0 []task.Task
	if rf, ok := ret.Get(0).(func() []task.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
