// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	lxc "github.com/xabinapal/gopve/pkg/types/vm/lxc"

	qemu "github.com/xabinapal/gopve/pkg/types/vm/qemu"

	task "github.com/xabinapal/gopve/pkg/types/task"

	vm "github.com/xabinapal/gopve/pkg/types/vm"
)

// VirtualMachine is an autogenerated mock type for the VirtualMachine type
type VirtualMachine struct {
	mock.Mock
}

// CreateLXC provides a mock function with given fields: opts
func (_m *VirtualMachine) CreateLXC(opts lxc.CreateOptions) (task.Task, error) {
	ret := _m.Called(opts)

	var r0 task.Task
	if rf, ok := ret.Get(0).(func(lxc.CreateOptions) task.Task); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(lxc.CreateOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateQEMU provides a mock function with given fields: opts
func (_m *VirtualMachine) CreateQEMU(opts qemu.CreateOptions) (task.Task, error) {
	ret := _m.Called(opts)

	var r0 task.Task
	if rf, ok := ret.Get(0).(func(qemu.CreateOptions) task.Task); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(qemu.CreateOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLXC provides a mock function with given fields: vmid, purge, force
func (_m *VirtualMachine) DeleteLXC(vmid uint, purge bool, force bool) (task.Task, error) {
	ret := _m.Called(vmid, purge, force)

	var r0 task.Task
	if rf, ok := ret.Get(0).(func(uint, bool, bool) task.Task); ok {
		r0 = rf(vmid, purge, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, bool, bool) error); ok {
		r1 = rf(vmid, purge, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteQEMU provides a mock function with given fields: vmid, purge, force
func (_m *VirtualMachine) DeleteQEMU(vmid uint, purge bool, force bool) (task.Task, error) {
	ret := _m.Called(vmid, purge, force)

	var r0 task.Task
	if rf, ok := ret.Get(0).(func(uint, bool, bool) task.Task); ok {
		r0 = rf(vmid, purge, force)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, bool, bool) error); ok {
		r1 = rf(vmid, purge, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: vmid
func (_m *VirtualMachine) Get(vmid uint) (vm.VirtualMachine, error) {
	ret := _m.Called(vmid)

	var r0 vm.VirtualMachine
	if rf, ok := ret.Get(0).(func(uint) vm.VirtualMachine); ok {
		r0 = rf(vmid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vm.VirtualMachine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(vmid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *VirtualMachine) List() ([]vm.VirtualMachine, error) {
	ret := _m.Called()

	var r0 []vm.VirtualMachine
	if rf, ok := ret.Get(0).(func() []vm.VirtualMachine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vm.VirtualMachine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByKind provides a mock function with given fields: kind
func (_m *VirtualMachine) ListByKind(kind vm.Kind) ([]vm.VirtualMachine, error) {
	ret := _m.Called(kind)

	var r0 []vm.VirtualMachine
	if rf, ok := ret.Get(0).(func(vm.Kind) []vm.VirtualMachine); ok {
		r0 = rf(kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vm.VirtualMachine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(vm.Kind) error); ok {
		r1 = rf(kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
