// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	request "github.com/xabinapal/gopve/pkg/request"

	url "net/url"
)

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

// EndAtomicBlock provides a mock function with given fields:
func (_m *Executor) EndAtomicBlock() {
	_m.Called()
}

// Request provides a mock function with given fields: method, _a1, form
func (_m *Executor) Request(method string, _a1 string, form url.Values) ([]byte, error) {
	ret := _m.Called(method, _a1, form)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, url.Values) []byte); ok {
		r0 = rf(method, _a1, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, url.Values) error); ok {
		r1 = rf(method, _a1, form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAuthenticationTicket provides a mock function with given fields: ticket, method
func (_m *Executor) SetAuthenticationTicket(ticket string, method request.AuthenticationMethod) {
	_m.Called(ticket, method)
}

// SetCSRFToken provides a mock function with given fields: token
func (_m *Executor) SetCSRFToken(token string) {
	_m.Called(token)
}

// StartAtomicBlock provides a mock function with given fields:
func (_m *Executor) StartAtomicBlock() {
	_m.Called()
}
